# Generated by Django 6.0.5 on 2026-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('skills', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('about', models.TextField()),
            ],
        ),
    ]
